BlackmoorHold/Blackmoor-hold

code/game/objects/items/rogueweapons/melee/swords.dm, code/modules/jobs/job_types/roguetown/Inquisition/puritan.dm
=> Neo Request 1 / Your God is Dead

code/modules/client/preferences.dm, code/modules/client/preferences_savefile.dm, code/modules/mob/living/carbon/human/examine.dm, code/modules/mob/living/carbon/human/human_defines.dm, code/modules/mob/living/carbon/human/human_topic.dm
=> NSFW Headshots and tiny headshot icons on examine

code/modules/jobs/job_types/roguetown/courtier/jester.dm
Changes it so that jester isn't locked to RACES_TOLERATED_UP
I think it's pretty funny.
=> Allows furries to be jesters.

code/game/objects/structures.dm, code/game/turfs/closed/_closed.dm
Running into things no longer knockdown but still daze people on foot.
It was annoying, it still briefly stuns as before and damages the head the same.
=> running into things dont knockdown

code/datums/stress/negative_events.dm
Nobles bitch for a shorter time now about everything and are less likely to get a heart attack due to eating some peasant food after being hungry.
Virginity loss on churchies is no longer a permanent heart attack inflicting debuff but instead 15 minutes of heart attack stress.
I dont even know what to say.
=> Less bitching for nobles and church virgins

code/modules/roguetown/roguemachine/titan.dm
=> Blackmoor8

interface/skin.dmf
Like why is it even dogshit like that.
Easier for admins to find verbs and players aswell.
=> Makes say bar of the chat be used for commands like everywhere else

code/game/turfs/closed/minerals.dm
Ports this code: https://github.com/Rotwood-Vale/Ratwood-Keep/pull/2925 adapts it to use roguestam (same var different name it seems)
Already in RW and has worked for 2 weeks now.
Stops hands hurting.
=> Adds auto mining mineral walls.

code/modules/spells/roguetown/acolyte/general.dm, modular_azurepeak/code/modules/spells/pantheon/inhumen/matthios.dm
Healslut viability has never been so high
=> Miracles automatically target and heal the most damaged limb

code/game/objects/items/rogueweapons/melee/swords.dm
The PR goal is to add variety between the swords, even with slight degrees of purpose.
- Iron arming sword.
Given integrity of 135.
Defense 4 > 4.5. (the 0.5 is a 5% increase)
- Arming sword.
Integrity 150 > 175.
Defense 4 > 4.5. (the 0.5 is a 5% increase)
Strength requirement 7 < 6.
- Falchion.
Defense 6 > 6.5.
Given integrity of 250. (the blade is thick like really thick)
- Falx.
Defense 6 < 5. (Just search it up, it really doesn't feel like it should have a default 60% parry chance)
- Iron shortsword.
Given integrity of 135.
Defense 3 > 3.5.
- Steel shortsword.
Defense 4 > 4.5.
- Shamshir.
Given integrity of 230.
Defense 6 > 6.5.
- Copper messer.
Defense 2 > 2.5.
- Iron messer.
Given Integrity of 160.
- Steel messer.
Given integrity of 180.
- Krieg messer.
Given integrity of 190.
- …
=> Swords n' parrying integrity

code/__HELPERS/lordcolor.dm
Changes the default keep's colors to black and red
Tested on localhost
It's better than white and blue
=> Change keep colors

code/modules/cargo/packsrogue/merchant/armor.dm, code/modules/clothing/rogueclothes/neck.dm, code/modules/clothing/rogueclothes/wrists.dm, code/modules/roguetown/roguecrafting/leather/leather_armor_recipes.dm, code/modules/roguetown/roguecrafting/sewing.dm, code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
Reverts BlackmoorHold/Blackmoor-hold#74
=> Revert "Armorer's Touch: Wrists and Neck edition"

code/modules/jobs/job_types/roguetown/nobility/bailiff.dm
Marshals are tolerated races and up
Tested on localhost
Pretty sure this is just an oversight
=> Marshal tolerated+

code/datums/mind.dm, code/modules/cargo/packsrogue/merchant/luxury.dm, code/modules/roguetown/roguecrafting/alchemy/alch_items.dm
this is very wholesome. i think eora would approve.
=> Readds love potions

code/modules/roguetown/roguecrafting/structure.dm
=> Pillories can be crafted

code/modules/mob/living/carbon/life.dm, code/modules/roguetown/roguecrafting/structure.dm
=> leaning against a wall will cause you to (VERY) slowly regain fatigue

code/modules/roguetown/roguecrafting/alchemy/reagents.dm
I think the issue with potions was i made strong health pots too weak due a mindfuck thinking it lasts as long as normal potions.
Testing is for the weka
Stronk health pot is stronk now
=> health pot fix

code/modules/cargo/packsrogue/merchant/armor.dm, code/modules/clothing/rogueclothes/neck.dm, code/modules/clothing/rogueclothes/wrists.dm, code/modules/roguetown/roguecrafting/leather/leather_armor_recipes.dm, code/modules/roguetown/roguecrafting/sewing.dm, code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
Reverts BlackmoorHold/Blackmoor-hold#90
=> Revert "Revert "Armorer's Touch: Wrists and Neck edition"" (Other words a hotfix)

code/modules/spells/roguetown/acolyte/dendor.dm
=> makes the cooldown for beast form 3 minutes

code/modules/jobs/job_types/roguetown/church/monk.dm
why do they not already have this
=> acolytes get enough medicine to reattach limbs

modular_azurepeak/code/datums/loadout.dm
=> Adds the spellcaster equipment to the loadout

code/game/objects/structures/mineral_doors.dm
https://github.com/BlackmoorHold/Blackmoor-hold/pull/38
=> Resubmit of #38

modular_azurepeak/virtues/utility.dm
Adds the Ritualist virtue. 
It gives you the Ritualist trait, and a stashed ritual chalk.
Your neighbor could be a lich. You never know these days.
=> Adds Ritualist virtue

code/modules/jobs/job_types/roguetown/adventurer/wretch.dm
i fucked that pr by accidentally pushing a bunch of unrelated things to into the branch
https://github.com/BlackmoorHold/Blackmoor-hold/pull/82
=> resubmit of #92

code/modules/jobs/job_types/roguetown/mercenaries/classes/condottiero.dm, code/modules/jobs/job_types/roguetown/mercenaries/classes/grudgebearer.dm
What it says on the tin.
Like 2-3 number and word changes, ran without error.
Grudgebearer fucking NEVER broke and with some intents missing on it's system (custom to the armor set) it so this is a bandaid fix.
Also crossbow merc was well beneath the wrestling skill of literally every other sort of merc class of it's type, so it was bleak milord.
=> Makes Etruscan Crossbowman not abysmal dogshit and a bandaid fix Grudgebearer

code/modules/clothing/rogueclothes/armor.dm, code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
I am going to find a way to make bikinis more easily accessible. you cannot stop me.
=> Amazon subclass + makes kinis reapairable

code/modules/jobs/job_types/roguetown/yeomen/merchant.dm
The merchant were unable to laugh, scream or use any noises
https://github.com/user-attachments/assets/c65526f1-0196-4729-9e15-2fb3813d860a
Laughing should be for all.
=> Merchant noises bugfix

_maps/map_files/dun_world/dun_world.dmm
Ever tired of seeing the Orc Dungeon, and thinking to yourself. Huh, this doesnt feel like a generic orc fantasy dungeon. Where are the pallisades? Where are the Tents! The shitty living conditions!
Well ive got the solution for you. Adds in another mini dungeon in the forests, giving for more reasons to travel south the town.
Current Random Loot Spawns
1 Medical
2 Tool
1 Armor
1 Weapon
The rest being sewer
Not meant to be the best quality of dungeon related items. But just a mini dungeon around for people to explore.
(Will be working on more map changes to come for quality of life, and such)
Images:
https://media.discordapp.net/attachments/1163816776920993802/1387721623112646746/Screenshot_2025-06-26_180837.png?ex=685e5ff9&is=685d0e79&hm=c239cfa905f229a2200763644a026a47a8e5f67768b39cf3e54 …
=> Another Mini Dungeon in the Forests

code/modules/antagonists/roguetown/villain/vampire.dm, code/modules/antagonists/roguetown/villain/werewolf/werewolf.dm, code/modules/antagonists/roguetown/villain/werewolf/werewolf_spells.dm, code/modules/antagonists/roguetown/villain/werewolf/werewolf_transformation.dm, code/modules/antagonists/roguetown/villain/werewolf/werewolf_wound_infection.dm, code/modules/jobs/job_types/roguetown/adventurer/wretch.dm, code/modules/mob/living/grabbing.dm
Wretch vampires and werewolves are now marked with a wretch_antag
Wretch vampires:
Cannot sire more vampires
Max blood/vitae is 5000, drains at 2/sec
Do not vomit when drinking blood
Still have access to regeneration and undead eyes
Wretch werewolves:
Cannot infect others
Cannot use howl
=> Wretches can be supernatural monsters

code/modules/jobs/job_types/roguetown/adventurer/wretch.dm
=> vampire wretches get vampire traits

code/modules/clothing/rogueclothes/wrists.dm
No more getting your fucking arms cut off through bracers anymore
armor should do armor things
=> Azure Slop Fix - Bracers now actually work

code/modules/jobs/job_types/roguetown/adventurer/types/wretch/lunacy_embracer.dm, roguetown.dme
Made with werewolf wretch in mind
https://www.youtube.com/watch?v=2gv_Uil_62k&list=RD2gv_Uil_62k&start_radio=1
=> Lunacy embracer wretch
